CREATE TABLE CATEGORY{
    ID SERIAL PRIMARY KEY NOT NULL UNIQUE,
    NAME VARCHAR(200) NOT NULL,
    UNITY VARCHAR(200) NOT NULL,
}
CREATE TABLE QUESTION{
    ID SERIAL PRIMARY KEY NOT NULL UNIQUE,
    ID_CATEGORY INT REFERENCES CATEGORY(ID) NOT NULL,
    QUESTION VARCHAR(200) NOT NULL
}
CREATE TABLE ANSWER{
    ID SERIAL PRIMARY KEY NOT NULL UNIQUE,
    ID_QUESTION INT REFERENCES QUESTION(ID) NOT NULL,
    ANSWER VARCHAR(200) NOT NULL,
    NATURE BOOLEAN NOT NULL
}
/*
CATEGORYS
*/
INSERT INTO CATEGORY (NAME,UNITY) VALUES ('','')

/*QUESTIONS & ANSWERS*/
/*CATEGORY X*/
/*Q1*/
INSERT INTO QUESTION (ID_CATEGORY,QUESTION) VALUES ('','')
/*ANSWERS*/
INSERT INTO ANSWER (ID_QUESTION,ANSWER,NATURE) VALUES ('','','')